package prin;

import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JTable extends javax.swing.JFrame {
   
   Conexion conexion1 = new Conexion();
   Connection connection;
   DefaultTableModel modelo;
   
   Statement statement;
   
   ResultSet resultSet;
   int idc;
   
   public JTable() {
      initComponents();
      setLocationRelativeTo(null);
      consultar();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane2 = new javax.swing.JScrollPane();
      jTable2 = new javax.swing.JTable();
      jRadioButton1 = new javax.swing.JRadioButton();
      jPanel1 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      txtNombre = new javax.swing.JTextField();
      txtApellido = new javax.swing.JTextField();
      txtId = new javax.swing.JTextField();
      txtEdad = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jButtonAgregar = new javax.swing.JButton();
      jButtonModificar = new javax.swing.JButton();
      jButtonEliminar = new javax.swing.JButton();
      jButtonNuevo = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      Tabla = new javax.swing.JTable();

      jTable2.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "ID", "Nombre", "Apellidos", "Edad"
         }
      ));
      jScrollPane2.setViewportView(jTable2);

      jRadioButton1.setText("jRadioButton1");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

      jLabel2.setText("ID:");

      jLabel3.setText("Nombre:");

      jLabel4.setText("Apellido:");

      jLabel5.setText("Edad:");

      txtApellido.setToolTipText("");

      txtId.setEditable(false);
      txtId.setEnabled(false);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel2)
                  .addGap(52, 52, 52)
                  .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addGap(18, 18, 18)
                  .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel4)
                     .addComponent(jLabel5))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtApellido)
                     .addComponent(txtEdad))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jLabel1.setText("CLIENTES");

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

      jButtonAgregar.setText("Agregar");
      jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAgregarActionPerformed(evt);
         }
      });

      jButtonModificar.setText("Modificar");
      jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonModificarActionPerformed(evt);
         }
      });

      jButtonEliminar.setText("Eliminar");
      jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEliminarActionPerformed(evt);
         }
      });

      jButtonNuevo.setText("Limpiar");
      jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonNuevoActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jButtonAgregar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
            .addComponent(jButtonModificar)
            .addGap(39, 39, 39)
            .addComponent(jButtonEliminar)
            .addGap(27, 27, 27)
            .addComponent(jButtonNuevo)
            .addGap(20, 20, 20))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(24, Short.MAX_VALUE))
      );

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Registros")));

      Tabla.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "ID", "Nombre", "Apellidos", "Edad"
         }
      ));
      Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            TablaMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(Tabla);

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(107, 107, 107))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(208, 208, 208)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
      // TODO add your handling code here:
      agregar();
      consultar();
   }//GEN-LAST:event_jButtonAgregarActionPerformed

   private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
      modificar(); 
      consultar();

      // TODO add your handling code here:
   }//GEN-LAST:event_jButtonModificarActionPerformed

   private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
      eliminar();
      consultar();
      // TODO add your handling code here:
   }//GEN-LAST:event_jButtonEliminarActionPerformed

   private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
      nuevoCliente();
      consultar();
      // TODO add your handling code here:
   }//GEN-LAST:event_jButtonNuevoActionPerformed

   private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
      int fila = Tabla.getSelectedRow();
      if(fila == -1){
         JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada");
     
      }else{
         idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
         String nombre = (String) Tabla.getValueAt(fila, 1);
         String apellido = (String) Tabla.getValueAt(fila, 2);
         int edad = Integer.parseInt((String) Tabla.getValueAt(fila, 3).toString());
         txtId.setText(""+idc);
         txtNombre.setText(nombre);
         txtApellido.setText(apellido);
         txtEdad.setText(""+edad);
      }
      
   }//GEN-LAST:event_TablaMouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(JTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(JTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(JTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(JTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new JTable().setVisible(true);
         }
      });
   }
   
   void consultar(){
      String sql = "select * from clientes";
      try {
         connection = conexion1.getConnection();
         statement = connection.createStatement();
         resultSet = statement.executeQuery(sql);
         Object[] cliente = new Object[4];
         modelo = (DefaultTableModel) Tabla.getModel();
         
         while (resultSet.next()) {            
            cliente[0] = resultSet.getInt("id_cliente");
            cliente[1] = resultSet.getString("nombre_cliente");
            cliente[2] = resultSet.getString("apellido_cliente");
            cliente[3] = resultSet.getInt("edad_cliente");
            
            modelo.addRow(cliente);
         }
         Tabla.setModel(modelo);
         
      } catch (Exception e) {
      }
      
   }
   
   void agregar(){
      String nombre = txtNombre.getText();
      String apellido = txtApellido.getText();
      String edad = txtEdad.getText();

      try {
         if (nombre.equals("")|| apellido.equals("") || edad.equals("")) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacíos");
         }if(nombre.length()>14){
            JOptionPane.showMessageDialog(null,"El nombre no puede superar los 14 caractéres");
         }if(apellido.length()>14){
            JOptionPane.showMessageDialog(null,"El apellido no puede superar los 14 caractéres");
         }if(edad.length()>3){
            JOptionPane.showMessageDialog(null,"La no puede superar lo 3 dígitos");
         }else
         {
            String sql = "insert into clientes (nombre_cliente, apellido_cliente, edad_cliente) values ('" + nombre + "','" + apellido+"','" + edad + "');";
         connection = conexion1.getConnection();
         statement = connection.createStatement( );
         statement.executeUpdate(sql);
         JOptionPane.showConfirmDialog(null,"Nuevo cliente registrado");
         }
         limpiarTabla();
         limpiarCajas();
      } catch (Exception e) {
         e.printStackTrace();
      }
   }
   
   void modificar(){
      String nombre = txtNombre.getText();
      String apellido = txtApellido.getText();
      String edad = txtEdad.getText();
      
      try {
         if (nombre.equals("")|| apellido.equals("") || edad.equals("")) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacíos");
         }else
         {
            String sql = "update clientes set id_cliente = " + idc + ", nombre_cliente = '" + nombre +"', apellido_cliente = '" + apellido + "',edad_cliente ="+edad+" where id_cliente = "+idc+";";
         connection = conexion1.getConnection();
         statement = connection.createStatement( );
         statement.executeUpdate(sql);
         JOptionPane.showConfirmDialog(null,"Datos de cliente modificados");
         }
         limpiarTabla();
         limpiarCajas();
      } catch (Exception e) {
         e.printStackTrace();
      }
   }
   
   void eliminar(){
      int fila = Tabla.getSelectedRow();
      try {
         if (fila<0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente");
         }else{
            String sql = "delete from clientes where id_cliente = "+idc;
                     connection = conexion1.getConnection();
         statement = connection.createStatement( );
         statement.executeUpdate(sql);
         JOptionPane.showConfirmDialog(null,"Datos de cliente eliminados");
         }
         limpiarTabla();
         limpiarCajas();
      } catch (Exception e) {
         e.printStackTrace();
      }
   }
   
   void limpiarCajas(){
            txtId.setText("");
      txtNombre.setText("");
      txtApellido.setText("");
      txtEdad.setText("");
   }
   
   void nuevoCliente(){
      limpiarCajas();
      txtNombre.requestFocus();
      txtApellido.requestFocus();
      txtEdad.requestFocus();
      limpiarTabla();
      
   }
   
   void limpiarTabla()
   {
      for (int i = 0; i < Tabla.getRowCount(); i++) {
         modelo.removeRow(i);
         i--;
      }
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTable Tabla;
   private javax.swing.JButton jButtonAgregar;
   private javax.swing.JButton jButtonEliminar;
   private javax.swing.JButton jButtonModificar;
   private javax.swing.JButton jButtonNuevo;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JRadioButton jRadioButton1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTable jTable2;
   private javax.swing.JTextField txtApellido;
   private javax.swing.JTextField txtEdad;
   private javax.swing.JTextField txtId;
   private javax.swing.JTextField txtNombre;
   // End of variables declaration//GEN-END:variables
}
